Major Version Bump 4
aws/aws-dotnet-extensions-configuration pull request #103
Opened 2022-02-14 07:48 UTC by normj

## Description
This is a consolidation of the open PRs which have some new features and require some breaking changes. Due to the age of the PRs and AWS AppConfig changing to a new API pattern the PRs needed some rework. Instead of asking the original PR owners to come back to the PRs after they have been sitting idle for so long I made the changes directly in this combined PR.

## Consolidated PRs
* [#99](https://github.com/aws/aws-dotnet-extensions-configuration/pull/99) - Added support for using AWS AppConfig's Lambda extension layer to reload the config values. Since the PR was originally submitted AppConfig has switched to a new pattern of using the separate service client IAmazonAppConfigData. I have updated the PR to use the new API and made several other adjustments to smooth out the registration of using the extension. I did not include the sample app from the original PR because it needed a docs and I would like to add a sample using our new `Amazon.Lambda.Annotations` library once we GA that library.
* [#69](https://github.com/aws/aws-dotnet-extensions-configuration/pull/69) - Allow the processing or parameters from SSM parameter store to more customizable.
* [#59](https://github.com/aws/aws-dotnet-extensions-configuration/pull/59) - Switch to using System.Text.Json instead of Newtonsoft

## Breaking Changes
* Property `ClientId` was removed from `AppConfigConfigurationSource` because it is not longer used in the new AppConfig Data APIs
* When using AppConfig IAM permissions for `appconfig:StartConfigurationSession` and `appconfig:GetLatestConfiguration` are now required and `appconfig:GetConfiguration` is not longer required.
* Updated the minimum version of .NET to be .NET Core 3.1
* The `IncludeParameter`, `GetKey` and `GetValue` methods were removed from `IParameterProcessor` in favor of the new generic `ProcessParameters` method allowing more flexibility in implementations.

## Testing
PRs added tests and I added more tests as well. Also used the library in deployed applications and ensure configuration values were propagated and correctly reloaded with values in AWS changed.

2022-02-14 14:15 UTC, mgorski-mg approved these changes
Really good job! 🚀

2022-02-14 14:15 UTC, mgorski-mg commented on README.md
> +
one spare empty line

2022-02-14 18:27 UTC, normj commented on README.md
> +
Removed

2022-02-14 18:27 UTC, normj commented on README.md
> +The `reloadAfter` parameter on `AddSystemsManager()` and `AddAppConfig()` enables automatic reloading of configuration data from Parameter Store or AppConfig as a background task. When using
Removed

2022-02-14 18:29 UTC, normj commented on src/Amazon.Extensions.Configuration.SystemsManager/AppConfig/AppConfigForLambdaExtensions.cs
> +
Removed

2022-02-14 19:25 UTC, normj commented on src/Amazon.Extensions.Configuration.SystemsManager/AppConfig/AppConfigProcessor.cs
> +                _lambdaExtensionClient = new HttpClient();
Good call. I added the `CustomHttpClientForLambdaExtension` property to `AppConfigConfigurationSource` to allow customizing the client with potentially X-Ray.

2022-02-15 19:28 UTC, ganeshnj requested changes

2022-02-15 19:28 UTC, ganeshnj commented on src/Amazon.Extensions.Configuration.SystemsManager/AppConfig/AppConfigForLambdaExtensions.cs
> +                source.ReloadAfter = TimeSpan.FromSeconds(reloadAfter);
```suggestion
                // default polling duration is 45 seconds https://docs.aws.amazon.com/appconfig/latest/userguide/appconfig-integration-lambda-extensions.html
                var reloadAfter = 45;

                // Since the user is using Lambda extension which automatically refreshes the data default to the configuration provider defaulting
                // to reload at the rate the extension reloads plus 5 second buffer.
                var reloadAfterStr = Environment.GetEnvironmentVariable("AWS_APPCONFIG_EXTENSION_POLL_INTERVAL_SECONDS");
                if (reloadAfterStr != null && !int.TryParse(reloadAfterStr, out reloadAfter))
                {
                    throw new ArgumentException("Environment variable AWS_APPCONFIG_EXTENSION_POLL_INTERVAL_SECONDS used for computing ReloadAfter is not set to a valid integer");
                }

                reloadAfter += 5;
                source.ReloadAfter = TimeSpan.FromSeconds(reloadAfter);
```

2022-02-15 19:28 UTC, ganeshnj commented on src/Amazon.Extensions.Configuration.SystemsManager/Internal/JsonConfigurationParser.cs
> +                    break;
nit: not needed, as switch case is exhaustive. Not putting `default` usually helpful during static analysis.

When new values are added to the enum, they are shown as errors and forces to adapt code based on the newly added enum value.

2022-02-15 19:28 UTC, ganeshnj commented on src/Amazon.Extensions.Configuration.SystemsManager/Internal/JsonConfigurationParser.cs
> +        }
What is being disposed here? Is this even required?

2022-02-15 19:28 UTC, ganeshnj commented on src/Amazon.Extensions.Configuration.SystemsManager/Internal/SystemsManagerProcessor.cs
> +                return AddPrefix(Source.ParameterProcessor.ProcessParameters(Enumerable.Repeat(response.Parameter, 1), Source.Path), prefix);
nit
```suggestion
                return AddPrefix(Source.ParameterProcessor.ProcessParameters(new []{response.Parameter}, Source.Path), prefix);
```

2022-02-15 19:28 UTC, ganeshnj commented on test/Amazon.Extensions.Configuration.SystemsManager.Integ/AppConfigEndToEndTests.cs
> +                await Task.Delay(10);
nit: for readability
```suggestion
                await Task.Delay(TimeSpan.FromMilliseconds(5));

```

2022-02-15 20:12 UTC, mgorski-mg commented on src/Amazon.Extensions.Configuration.SystemsManager/AppConfig/AppConfigConfigurationSource.cs
> +        public HttpClient CustomHttpClientForLambdaExtension { get; set; }
I think both are needed because you don't need to customize HttpClient when you want to go for the Lambda version.
`UseLambdaExtension` is set automatically when you are using `AddAppConfigUsingLambdaExtension`.

2022-02-23 06:10 UTC, normj commented on README.md
> +For improved performance with AppConfig and Lambda it is recommended to use the `AddAppConfigUsingLambdaExtension` method and deploy the Lambda funtion with the AWS AppConfig Lambda extension. More i
Fixed

2022-02-23 06:19 UTC, normj commented on src/Amazon.Extensions.Configuration.SystemsManager/AppConfig/AppConfigConfigurationSource.cs
> +        public HttpClient CustomHttpClientForLambdaExtension { get; set; }
Agreed, using a custom HttpClient is an advanced use case and I don't want to make that the decider to use the Lambda extension.

2022-02-23 06:33 UTC, normj commented on test/Amazon.Extensions.Configuration.SystemsManager.Integ/AppConfigEndToEndTests.cs
> +                await Task.Delay(10);
Funny that you are right about the readability. It was actually supposed to be seconds since ConfigurationProvider reloads every 5 seconds. Adjusted to 7 seconds.

2022-02-23 06:35 UTC, normj commented on src/Amazon.Extensions.Configuration.SystemsManager/Internal/JsonConfigurationParser.cs
> +                    break;
Removed

2022-02-23 06:37 UTC, normj commented on src/Amazon.Extensions.Configuration.SystemsManager/Internal/JsonConfigurationParser.cs
> +        }
Removed

2022-02-23 16:53 UTC, ganeshnj commented on test/Amazon.Extensions.Configuration.SystemsManager.Integ/AppConfigEndToEndTests.cs
> +                await Task.Delay(10);
:O 

[Task.Delay](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.delay?view=net-6.0#system-threading-tasks-task-delay(system-int32)) actually takes milliseconds, glad we caught this. Yet another reason of using `TimeSpan`.

2022-02-23 16:55 UTC, ganeshnj approved these changes

2022-02-24 05:48 UTC, cfbao commented
Secrets Manager path is now incompatible with `DefaultParameterProcessor` - its `IConfiguration` path will always contain a section name of empty string

repro:
```csharp
var config = new ConfigurationBuilder().AddSystemsManager(
	source => {
		source.Path = "/aws/reference/secretsmanager/config-extension-test";
		source.ParameterProcessor = new DefaultParameterProcessor();
		source.Prefix = "random-prefix";
	} )
	.Build();

foreach( var (k, v) in config.AsEnumerable() ) {
	Console.WriteLine( $"|{k}|{v}|" );
}
```
output
```
|random-prefix||
|random-prefix:|{"hello":"world2"}|
```

`AddPrefix` should probably check for keys that are empty strings?

noticed this because I'm working on #107

2022-03-03 14:56 UTC, warej approved these changes
I have reviewed the code coming from my PR. A lot of time has passed, but as far as I remember how it works, it is all good.

2022-04-13 00:50 UTC, normj commented
@cfbao I don't understand your issue. The `|random-prefix||` line in your output is representing the config section `random-prefix`. That is just an artifact of how the `AsEnumerable` method works. Further the intention for secrets manager is to use the `JsonParameterProcessor` processor. I saw your draft PR but its default behavior is the same as what is going in this branch. The only difference is you provide an explicit override to use `SingleParameter`.

2022-04-14 06:35 UTC, merged

2022-04-14 06:36 UTC, normj commented
Merged into master and working on getting master released.

2022-04-17 15:00 UTC, cfbao commented
> The `|random-prefix||` line in your output is representing the config section `random-prefix`. That is just an artifact of how the `AsEnumerable` method works.

Yes `|random-prefix||` is representing the config section, and that's my issue - I was expecting the value to be under the path `random-prefix` directly, not nested inside a section, with an empty string as property name.

To be more explicit, given the config in my sample code, `config["random-prefix"] )` is empty, but `config["random-prefix:"]` is the value in Secrets Manager.
i.e. The configuration is equivalent to this in `appsettings.json`:
```json
{
  "random-prefix": {
    "": "<value-in-secrets-manager>"
  }
}
```
This is not just an artifact of `AsEnumerable`.
I thought it'd make more sense for it to be equivalent to this instead
```json
{
  "random-prefix": "<value-in-secrets-manager>"
}
```

> Further the intention for secrets manager is to use the `JsonParameterProcessor` processor.

If it's the expressed intention to not support non-JSON value and `DefaultParameterProcessor` for Secrets Manager, then I don't have an issue technically speaking. It just seems a missed opportunity to me with this major version bump.

2022-05-04 19:39 UTC, gbd3-en commented
Is there a roadmap or ETA for when v4 will be released on NuGet?

2022-06-11 22:00 UTC, rinckd commented
Can you publish a preview version to NuGet with the current v4 changes?