Support TargetFramework of netstandard2.0 and version bump to 5.0.4.
aws/aws-dotnet-extensions-configuration pull request #150
Opened 2023-05-30 04:04 UTC by heatonmatthew

Update: Support the netstandard2.0 target framework (in addition to the existing ones)

## Description
I have a project where I need to use this library from .NET Framework for backward compatibility purposes. By conditionally referencing the `System.Text.Json` package, it's possible to build the entire solution to target netstandard2.0 and therefore be consumed from .NET Framework.

## Motivation and Context
The netstandard2.0 target framework allows this package to be used by additional .NET runtimes.  In my case, I need to run my solution under .NET Framework for legacy reasons.

The only issue was the `System.Text.Json` package which isn't included in the framework for netstandard2.0, but there is a Microsoft-supplied external package that can be used to support netstandard2.0.  By conditionally including this `PackageReference` it only affects the netstandard2.0 target (keeping the other targets using their internally included packages).

## Testing
Successfully ran the `Amazon.Extensions.Configuration.SystemsManager.Tests` unit test suite.

## Screenshots (if appropriate)
NA

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x ] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have read the **README** document
- [ ] I have added tests to cover my changes
- [x ] All new and existing tests passed

## License

- [ x] I confirm that this pull request can be released under the Apache 2 license

[issues]: https://github.com/aws/aws-dotnet-extensions-configuration/issues
[license]: http://aws.amazon.com/apache2.0/
[cla]: http://en.wikipedia.org/wiki/Contributor_License_Agreement

2023-05-30 04:48 UTC, normj commented
So you are using the `Microsoft.Extensions.Configuration` configuration framework in a .NET Framework application?

2023-05-30 22:13 UTC, heatonmatthew commented
> So you are using the `Microsoft.Extensions.Configuration` configuration framework in a .NET Framework application?

Yeah.  Long story, but we need to use some of the old capabilities of .NET Framework libraries that have been (rightly) removed in their .NET Core re-incarnation.  While being primarily a runtime, there are some Windows-specific capabilities that can only be accessed using it.

However, because .NET Framework 4.8 supports `netstandard2.0` we're able to use all the newer ecosystem to build the application itself (e.g. `Microsoft.Extensions.Configuration`, Kestrel, WebHost, etc).  Makes it a little less jarring.

2023-05-30 22:28 UTC, normj requested changes

2023-05-30 22:28 UTC, normj commented on RELEASE.CHANGELOG.md
> +﻿### Release 2023-05-30
Can you revert the changelog changes. We'll take care of getting that done as part of the release.

2023-05-30 22:28 UTC, normj commented on src/Amazon.Extensions.Configuration.SystemsManager/Amazon.Extensions.Configuration.SystemsManager.csproj
> +    <TargetFrameworks>netstandard2.0;netcoreapp3.1;net6.0</TargetFrameworks>
We haven't been doing much for .NET Standard 2.0 in awhile. I'm fine adding it in but just to prevent anybody thinking in the future of removing it in a major version bump can you add a XML comment here referencing this PR and the need for .NET Framework support.

2023-05-30 22:42 UTC, normj commented
> > So you are using the `Microsoft.Extensions.Configuration` configuration framework in a .NET Framework application?
> 
> Yeah. Long story, but we need to use some of the old capabilities of .NET Framework libraries that have been (rightly) removed in their .NET Core re-incarnation. While being primarily a runtime, there are some Windows-specific capabilities that can only be accessed using it.
> 
> However, because .NET Framework 4.8 supports `netstandard2.0` we're able to use all the newer ecosystem to build the application itself (e.g. `Microsoft.Extensions.Configuration`, Kestrel, WebHost, etc). Makes it a little less jarring.

Sounds like an interesting scenario. I'm fine adding the .NET Standard 2.0 support to unblock you. I just had a couple minor comments and then we can get this released.

2023-05-31 04:27 UTC, heatonmatthew commented
Great, thanks for that.

2023-05-31 05:38 UTC, normj approved these changes

2023-05-31 12:38 UTC, ashishdhingra approved these changes

2023-05-31 16:50 UTC, merged