Throw exception if duplicate Systems Manager parameter keys (case insensitive) are detected irrespective of whether the parameter is optional or not.
aws/aws-dotnet-extensions-configuration pull request #171
Opened 2024-06-11 17:24 UTC by ashishdhingra

## Description
Throw exception if duplicate Systems Manager parameter keys (case insensitive) are detected irrespective of whether the parameter is optional or not.

Kindly note that if keys are duplicated, .NET framework raises a generic `System.ArgumentException` with a message. We cannot use it since this exception could be thrown for other scenarios. Hence, added a new bare minimal `DuplicateParameterException` class.

## Motivation and Context
Issue #146 

## Testing
Added unit tests

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have read the **README** document
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

[issues]: https://github.com/aws/aws-dotnet-extensions-configuration/issues
[license]: http://aws.amazon.com/apache2.0/
[cla]: http://en.wikipedia.org/wiki/Contributor_License_Agreement

2024-06-14 23:11 UTC, normj requested changes

2024-06-14 23:11 UTC, normj commented on src/Amazon.Extensions.Configuration.SystemsManager/DefaultParameterProcessor.cs
> +                    if (result.Any(r => string.Equals(r.Key, parameterKey, StringComparison.OrdinalIgnoreCase)))
Why are we not doing the same as `if` block which seems more useful adding all the different cased parameter keys to the exception message?

2024-06-14 23:11 UTC, normj commented on src/Amazon.Extensions.Configuration.SystemsManager/DuplicateParameterException.cs
> +    public class DuplicateParameterException : ArgumentException
Needs docs explaining how this exception is thrown if duplicates are retrieved in AWS and explaining about the difference between casing with AWS and .NET Configuration.

2024-06-17 17:08 UTC, ashishdhingra commented on src/Amazon.Extensions.Configuration.SystemsManager/DuplicateParameterException.cs
> +    public class DuplicateParameterException : ArgumentException
Fixed in latest commit. Please review.

2024-06-19 05:02 UTC, normj commented on src/Amazon.Extensions.Configuration.SystemsManager/DefaultParameterProcessor.cs
> +                    if (result.Any(r => string.Equals(r.Key, parameterKey, StringComparison.OrdinalIgnoreCase)))
I'm good with not adding the overhead

2024-06-19 16:28 UTC, muhammad-othman approved these changes

2024-06-19 20:20 UTC, merged