Parse Json param with fallback to default way of parsing i.e. string or stringList
aws/aws-dotnet-extensions-configuration pull request #181
Opened 2024-08-07 17:01 UTC by snigdhasjg

## Description
Processes a collection of AWS Systems Manager (SSM) Parameters Store parameters, converting them into a dictionary of strings. 

This method supports both JSON-formatted parameters as per `JsonParameterProcessor`. And plain string & StringList as per `DefaultParameterProcessor`. 

The resulting dictionary keys are case-insensitive, as the other 2 implemenation.

## Motivation and Context
We have multiple types of SSM gets loaded during application startup.
Mainly Json and Text based. Params are dynamic in nature, so no way to telling if its Json or Text.

We are using this code for more than a week now, so why not merge it in the lib itself.

## Testing
1. Tested in our net8.0 application already. It runs on official docker image `mcr.microsoft.com/dotnet/aspnet:8.0-jammy`
2. Tested in net6.0 locally
3. Couldn't test on other 2 version for `netstandard2.0;netcoreapp3.1` as using ARM

Unit tests have been added, validated.

No impact on existing area as new implementation of the `IParameterProcessor`

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [x] I have read the **README** document
- [x] I have added tests to cover my changes
- [x] All new tests passed
- [ ] All existing tests passed

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

[issues]: https://github.com/aws/aws-dotnet-extensions-configuration/issues
[license]: http://aws.amazon.com/apache2.0/
[cla]: http://en.wikipedia.org/wiki/Contributor_License_Agreement

2024-08-07 17:20 UTC, normj commented on src/Amazon.Extensions.Configuration.SystemsManager/JsonOrDefaultParameterProcessor.cs
> +    public class JsonOrDefaultParameterProcessor : DefaultParameterProcessor
We need docs here explaining what this processor does. I would suggest instead of using the term `Default` here I would use `String`. So it is obvious to users that this supports either Json or falls back to String if the parameter fails to parse as Json.

2024-08-07 17:21 UTC, normj commented on src/Amazon.Extensions.Configuration.SystemsManager/JsonOrDefaultParameterProcessor.cs
> +                    var key = !string.IsNullOrEmpty(keyPrefix) ? ConfigurationPath.Combine(keyPrefix, kv.Key) : kv.Key;
Can you refactor this inner loop logic that is a duplicate inner loop logic in `JsonParameterProcessor` into a common internal utility method.

2024-08-07 17:31 UTC, snigdhasjg commented on src/Amazon.Extensions.Configuration.SystemsManager/JsonOrDefaultParameterProcessor.cs
> +    public class JsonOrDefaultParameterProcessor : DefaultParameterProcessor
Yeah I was thinking that, but then I hold myself cause it's both `String` and `StringList`

If you think `JsonOrStringParameterProcessor` would be good enough I can change that.

2024-08-07 17:34 UTC, snigdhasjg commented on src/Amazon.Extensions.Configuration.SystemsManager/JsonOrDefaultParameterProcessor.cs
> +                    var key = !string.IsNullOrEmpty(keyPrefix) ? ConfigurationPath.Combine(keyPrefix, kv.Key) : kv.Key;
Yeah I was thinking on the same line.

I have 3 static methods -
ParseJson can be used in both the new class and json processor.
Other 2 ParseString and ParseStringList can also be extracted out and reused.

Let me work on that

2024-08-07 18:15 UTC, snigdhasjg commented on src/Amazon.Extensions.Configuration.SystemsManager/JsonOrDefaultParameterProcessor.cs
> +    public class JsonOrDefaultParameterProcessor : DefaultParameterProcessor
Updated the name

2024-08-07 18:16 UTC, snigdhasjg commented on src/Amazon.Extensions.Configuration.SystemsManager/JsonOrDefaultParameterProcessor.cs
> +                    var key = !string.IsNullOrEmpty(keyPrefix) ? ConfigurationPath.Combine(keyPrefix, kv.Key) : kv.Key;
Extracted all 3 methods, 
refactored both `JsonParameterProcessor` and `DefaultParameterProcessor`

Waiting for your confirmation, post that will write tests for utility class

2024-08-07 18:26 UTC, normj commented on src/Amazon.Extensions.Configuration.SystemsManager/JsonOrDefaultParameterProcessor.cs
> +    public class JsonOrDefaultParameterProcessor : DefaultParameterProcessor
It is a valid concern that it is also doing `StringList` but I feel like `String` is better then `Default`. If I read the name `JsonOrDefault..` and ignore my knowledge of how things are implemented I would see a name that says Json or some unknown format.

2024-08-07 18:34 UTC, snigdhasjg commented on src/Amazon.Extensions.Configuration.SystemsManager/JsonOrDefaultParameterProcessor.cs
> +    public class JsonOrDefaultParameterProcessor : DefaultParameterProcessor
Yeah used `JsonOrStringParameterProcessor`

2024-08-07 20:26 UTC, snigdhasjg commented
Changes are done from my end. Once reviewed, I'll squash all commits.

2024-08-13 22:20 UTC, peterrsongg approved these changes
Checked out the branch, ran the tests myself. Looks good
```
Passed!  - Failed:     0, Passed:    74, Skipped:     0, Total:    74, Duration: 92 ms - Amazon.Extensions.Configuration.SystemsManager.Tests.dll (netcoreapp3.1)
Test run for C:\Dev\Repos\aws-dotnet-extensions-configuration\test\Amazon.Extensions.Configuration.SystemsManager.Tests\bin\Debug\net6.0\Amazon.Extensions.Configuration.SystemsManager.Tests.dll (.NETCoreApp,Version=v6.0)
Microsoft (R) Test Execution Command Line Tool Version 17.10.0 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.
```

2024-08-27 22:29 UTC, snigdhasjg commented
@normj @peterrsongg have't heard back. any update on this?

2024-10-22 08:09 UTC, snigdhasjg commented
@normj any update on this, when can this be merged?

2025-02-14 08:26 UTC, normj requested changes
Apologize for the delay. The changes look good but can you add a change file for the release? To do that add a file at `.autover/changes/<random-guid>.json` with the following content. Feel free to tweak the change log message.

```
{
  "Projects": [
    {
      "Name": "Amazon.Extensions.Configuration.SystemsManager",
      "Type": "Minor",
      "ChangelogMessages": [
        "Add opt-in JsonOrStringParameterProcessor processor supporting parameters being either strings or JSON"
      ]
    }
  ]
}
```

2025-02-17 20:16 UTC, snigdhasjg commented
@normj rebased and added the file `.autover/changes/44bf0928-edf9-4888-aebb-196b6364ffa8.json`

2025-02-20 20:54 UTC, normj approved these changes

2025-02-20 20:55 UTC, merged

2025-02-21 00:11 UTC, normj commented
PR was released today as part of version [6.3.0](https://github.com/aws/aws-dotnet-extensions-configuration/blob/master/CHANGELOG.md#amazonextensionsconfigurationsystemsmanager-630). Thanks for the PR!