feat: add support for .NET SDK V4
aws/aws-dotnet-extensions-configuration pull request #192
Opened 2024-10-16 21:40 UTC by philasmar

**Issue #, if available:**
DOTNET-7753

**Description of changes:**
* Updated the .NET SDK dependencies to the latest version 4.0.0-preview.4
* Marked project as trimmable
* Added SourceLink support

2024-10-16 21:56 UTC, 96malhar approved these changes

2024-10-16 23:44 UTC, normj requested changes
I think the `GetParametersByPathAsync` method in `SystemsManagerProcessor` needs a null check for the `response.Parameters` property.

Also I think the code is okay but for defensive code purposes in the `GetDataAsync` method of `AppConfigProcessor` maybe add `?? new Dictionary<string, string>` from the return of the private methods it calls.

2024-10-17 02:50 UTC, philasmar commented
> I think the `GetParametersByPathAsync` method in `SystemsManagerProcessor` needs a null check for the `response.Parameters` property.
> 
> Also I think the code is okay but for defensive code purposes in the `GetDataAsync` method of `AppConfigProcessor` maybe add `?? new Dictionary<string, string>` from the return of the private methods it calls.

Fixed

2024-10-17 06:13 UTC, normj approved these changes

2024-10-17 13:08 UTC, merged