Add AppConfig support
aws/aws-dotnet-extensions-configuration pull request #82
Opened 2021-01-11 22:30 UTC by mgorski-mg

## Description
Add AppConfig as another Systems Manager's source of configuration.

## Motivation and Context
It is extending the functionality for a new source of configuration.

## Testing
I created the ASP.NET app and configure it with AppConfig using this new extension.

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [x] I have updated the documentation accordingly
- [x] I have read the **README** document
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

[issues]: https://github.com/aws/aws-dotnet-extensions-configuration/issues
[license]: http://aws.amazon.com/apache2.0/
[cla]: http://en.wikipedia.org/wiki/Contributor_License_Agreement

2021-01-22 04:29 UTC, normj reviewed
I took a scan through the PR and it looks great. I need to do a deeper read through the code and try it out in action but wanted to give you some initial feedback that this looks like a great PR.

2021-01-22 06:32 UTC, normj requested changes

2021-01-22 06:32 UTC, normj commented on src/Amazon.Extensions.Configuration.SystemsManager/AppConfig/AppConfigProcessor.cs
> +                ClientId = Guid.NewGuid().ToString()
The Client ID should stay the same for the length of the process. This is going to report a different client id to AppConfig everytime there is a config reload.

2021-01-22 06:32 UTC, normj commented on src/Amazon.Extensions.Configuration.SystemsManager/AppConfig/AppConfigProcessor.cs
> +                return JsonConfigurationParser.Parse(response.Content);
ContentType needs to be checked to see if the content is JSON before parsing. If it is not JSON throw an error about it being an unsupported format.

2021-01-22 06:32 UTC, normj commented on src/Amazon.Extensions.Configuration.SystemsManager/AppConfig/AppConfigProcessor.cs
> +            var request = new GetConfigurationRequest
AppConfig is highly recommending using the ClientConfigurationVersion field to reduce repeatedly fetching the configuration causing extra charges. https://docs.aws.amazon.com/appconfig/2019-10-09/APIReference/API_GetConfiguration.html#appconfig-GetConfiguration-request-ClientConfigurationVersion

2021-01-24 12:30 UTC, mgorski-mg commented on src/Amazon.Extensions.Configuration.SystemsManager/AppConfig/AppConfigProcessor.cs
> +                ClientId = Guid.NewGuid().ToString()
Good catch! Changed to be created once per app launch while creating Source.

2021-01-24 12:30 UTC, mgorski-mg commented on src/Amazon.Extensions.Configuration.SystemsManager/AppConfig/AppConfigProcessor.cs
> +            var request = new GetConfigurationRequest
Fixed

2021-01-24 12:31 UTC, mgorski-mg commented on src/Amazon.Extensions.Configuration.SystemsManager/AppConfig/AppConfigProcessor.cs
> +                return JsonConfigurationParser.Parse(response.Content);
ContentType check added and NotImplementedException thrown for other ContentTypes than application/json.

2021-03-04 14:04 UTC, mgorski-mg commented
@normj do you have a while to check the requested changes? :)

2021-05-04 07:43 UTC, wojciech-dabrowski commented
@normj Any update on this? I'd love to use this functionality!

2021-08-19 01:08 UTC, normj approved these changes

2021-08-19 01:09 UTC, merged

2021-08-19 01:09 UTC, normj commented
Got the PR merged into master. I'll ping back when it is released which is what I'm focused on now.

2021-08-19 03:44 UTC, normj commented
Version 3.0.0 is released. Thanks so much for a cool feature and sorry for the delay getting it released.