Configuring AWSOptions
aws/aws-dotnet-extensions-configuration pull request #83
Opened 2021-01-19 04:37 UTC by bashatah

I explained how to configure AWSOptions which is used to create Systems Manager Client to README.md

## Description

I explained what AWSOptions does and how it is being used. I have also provided an example showing how it can be configured as part of appsettings.json

## Motivation and Context

It was not clear how someone can configure Systems Manager Client which is important to overcome some of the challenges when using the extension.

## Testing

I have implemented the steps I provided in README.md to fix the exception "Signature expired" which was returned every 30 mins from the lambda function, this fix required to set ResignRetries to true. after setting that configuration, my lambda stopped returning this exception.

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [x] I have updated the documentation accordingly
- [x] I have read the **README** document
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

[issues]: https://github.com/aws/aws-dotnet-extensions-configuration/issues
[license]: http://aws.amazon.com/apache2.0/
[cla]: http://en.wikipedia.org/wiki/Contributor_License_Agreement

2021-01-22 03:49 UTC, normj requested changes

2021-01-22 03:49 UTC, normj commented on README.md
> +			services.AddDefaultAWSOptions(Configuration.GetAWSOptions());
You actually don't need to do this step. It was required back in the 1.0 days of .NET Core when the service collection didn't have the IConfiguration. Around .NET Core 2.0 the default for the Host builders were to put the IConfiguration in the service collection. You only need to do this if you are doing something special.

2021-01-26 21:31 UTC, bashatah commented on README.md
> +			services.AddDefaultAWSOptions(Configuration.GetAWSOptions());
```suggestion

```

Removed the step as recommended

2021-02-06 06:30 UTC, boblodgett approved these changes

2021-07-21 01:31 UTC, ganeshnj approved these changes

2021-08-19 02:24 UTC, normj approved these changes

2021-08-19 02:28 UTC, merged

2021-08-19 02:29 UTC, normj commented
Thanks for the update